controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

client_info_test:
    path: /client/prenoms/{prenom}
    controller: App\Controller\ClientController::info
    requirements:
        prenom: '[a-zA-Z]+(-[a-zA-Z]+)*'

app_routes_php:
    resource: '../config/routes.php'
    type: php